Camera Сlass
anunknowperson/renderlib pull request #32
Opened 2024-10-02 17:11 UTC by DanielKorbelainen

Implemented core methods for handling the camera, including position, direction, velocity, and angle management (yaw and pitch). Added methods for updating the view matrix, processing SDL events, and getter/setter functions for camera properties.
Updated the logic in other parts of the project to ensure proper interaction with the new Camera class. Adjusted functions using the camera's position, velocity, and angles.

2024-10-04 16:12 UTC, anunknowperson commented
- в Cmake, не должно быть глобальных путей. Лучше вообще убрать изменения Cmake, им занимается Артем.

- В классе камеры должна быть только часть модели, только то что хранит данные, т.к. мы делаем MVC. то-есть, нужны только поля позиции, вращения, fov и т.д.

- по-сути, это должен быть маленький класс что-то вроде
#pragma once

#include <glm/glm.hpp>
#include <glm/gtc/matrix_transform.hpp>
#include <glm/gtc/quaternion.hpp>


class Light {
public:
    glm::vec3 position;
    float radius;
    float strength;
    glm::vec3 direction;
    glm::quat rotation;
    glm::vec3 color;

};


- тестировать модель невозможно, так как логики не должно быть. gtest сделать другую ишью и другой pull request.

- имплементация (установка позиции, повороты, look at, и т.д.) должны быть в отдельном классе CameraController, в отдельном PR.

2024-10-11 07:43 UTC, metrapoliten commented
Удали папку cmake-build*

2024-10-11 07:47 UTC, metrapoliten requested changes
- Удали папку cmake-build*
- Откати vcpkg.json

2024-10-11 17:06 UTC, metrapoliten commented on src/core/CameraController.h
> +    void setPitch(float newPitch);
Либо все set* вместе, либо для каждого X пиши пары вместе, чтобы лучше читалось
```cpp
T setX();
T getX();
```

либо
```cpp
T setX();
T setY();
T setZ();

T getX();
T getY();
...
```

2024-10-16 18:54 UTC, Tydik42 requested changes

2024-10-16 18:54 UTC, Tydik42 commented on Scene/SceneTests/CameraTest.cpp
Тесты должны лежать в корневой директории в папке tests. Можешь подтянуть последие изменения (pr Артёма)

2024-10-16 19:23 UTC, anunknowperson commented on Scene/SceneTests/CameraTest.cpp
Так, тут вообще тестов не должно быть.

2024-10-18 11:51 UTC, closed without merging