Move out basic pipelines
anunknowperson/renderlib pull request #37
Opened 2024-10-09 14:39 UTC by anunknowperson

2024-10-17 11:43 UTC, AnthonyRulez requested changes
Много лишних переводов строк. Слишком длинные методы. Метод не более одного экрана.

2024-10-17 11:45 UTC, AnthonyRulez requested changes
См. выше.

2024-12-06 03:30 UTC, metrapoliten requested changes

2024-12-06 03:30 UTC, metrapoliten commented on src/graphics/vulkan/vk_engine.cpp
> +    viewport.maxDepth = 1.f;
сделай обычную инициализацию структуры или designated

2024-12-06 03:30 UTC, metrapoliten commented on src/graphics/vulkan/vk_engine.cpp
> +    scissor.extent.height = _drawExtent.height;
используй designated initializer list

2024-12-06 03:30 UTC, metrapoliten commented on src/graphics/vulkan/vk_engine.cpp
> +    VkPresentInfoKHR presentInfo = {};
сделай обычную инициализацию структуры или designated

2024-12-06 03:30 UTC, metrapoliten commented on src/graphics/vulkan/vk_engine.cpp
> +        VkBufferImageCopy copyRegion = {};
сделай обычную инициализацию структуры или designated

2024-12-06 03:30 UTC, metrapoliten commented on src/graphics/vulkan/vk_engine.cpp
> +    memcpy(uploadbuffer.info.pMappedData, data, data_size);
добавь проверку на валидность указателей, иначе может быть UB

2024-12-06 03:30 UTC, metrapoliten commented on src/graphics/vulkan/vk_engine.h
> +        for (auto it = deletors.rbegin(); it != deletors.rend(); it++) {
Можно сократить, используя `<ranges>`, ещё добавил const &:
`for (const auto& el: deletors | std::views::reverse) { it(); }`

2024-12-13 01:00 UTC, anunknowperson commented on src/graphics/vulkan/pipelines.cpp
> +void Pipelines::init(VkDevice device,
Это не в конструкторе, потому что это должно выполняться в определенный момент, а объект создается сразу. Есть вариант перенести это в конструктор, но тогда нужно будет держать Pipelines как указатель и использовать new или умные указатели. Может так лучше, не знаю.

2024-12-13 01:03 UTC, anunknowperson commented on src/graphics/vulkan/pipelines.cpp
> +    vkDestroyPipelineLayout(_device, meshPipelineLayout, nullptr);
Здесь предполагается вынести две строки в отдельную функцию?

2024-12-13 01:07 UTC, anunknowperson commented on src/graphics/vulkan/vk_engine.cpp
> +    viewport.maxDepth = 1.f;
У нас есть C++ 20? если да, то можно заменить на новую.

если нет, то обычная инициализация выглядит нечитабельно (не понятно что есть что).

2024-12-13 01:07 UTC, anunknowperson commented on src/graphics/vulkan/vk_engine.cpp
> +    viewport.maxDepth = 1.f;
Пока что оставил как есть потому что непонятка со стандартом

2024-12-13 01:09 UTC, anunknowperson commented on src/graphics/vulkan/vk_engine.h
> +        for (auto it = deletors.rbegin(); it != deletors.rend(); it++) {
тот же вопрос про C++ 20

2024-12-13 01:11 UTC, anunknowperson commented on src/graphics/vulkan/vk_engine.h
> +        for (auto it = deletors.rbegin(); it != deletors.rend(); it++) {
(решено что C++ 20 есть)

2024-12-13 01:16 UTC, anunknowperson commented on src/graphics/vulkan/vk_engine.cpp
> +    viewport.maxDepth = 1.f;
done

2024-12-24 21:15 UTC, closed without merging

2024-12-24 21:16 UTC, anunknowperson commented
Закрыто потому что несколько попыток замержить на последние изменения оказались слишком сложны и отладить их не получилось, потратил много времени.