Add Light
anunknowperson/renderlib pull request #38
Opened 2024-10-10 18:09 UTC by anunknowperson

2024-10-10 18:09 UTC, anunknowperson commented
/summon tagir_garaev

2024-10-10 18:35 UTC, Tydik42 requested changes

2024-10-10 18:35 UTC, Tydik42 commented on CMakeLists.txt
Почему был удален этот кусок кода?

2024-10-10 18:35 UTC, Tydik42 commented on include/core/config.h
Файл `config.h` должен лежать в `.gitingore`. В нем лежит абсолютный путь к шейдерам, его не нужно добавлять в репозиторий. Нужно подтянуть изменения с main'а, либо добавить `include/core/.gitignore` с C++ template и вписать туда `/config.h`.

2024-10-10 18:35 UTC, Tydik42 commented on include/scene/interfaces/IController.h
Все интерфейсы MVC должны лежать в `include/interfaces`.

2024-10-10 19:21 UTC, Tydik42 requested changes

2024-10-10 19:21 UTC, Tydik42 commented on CMakeLists.txt
Почему был удален этот кусок кода?

2024-10-10 19:21 UTC, Tydik42 commented on include/core/config.h
Файл `config.h` должен лежать в `.gitingore`. В нем лежит абсолютный путь к шейдерам, его не нужно добавлять в репозиторий. Нужно подтянуть изменения с main'а, либо добавить `include/core/.gitignore` с C++ template и вписать туда `/config.h`.

2024-10-10 19:21 UTC, Tydik42 commented on include/scene/interfaces/IController.h
Все хедеры интерфейсов MVC должны лежать в `include/interfaces`

2024-10-17 11:40 UTC, AnthonyRulez requested changes

2024-10-17 11:40 UTC, AnthonyRulez commented on include/core/config.h
> +#define ASSETS_DIR "D:/renderlib/assets"
Пути только относительные.

2024-10-17 11:40 UTC, AnthonyRulez commented on include/scene/Light.h
> +class Light {
Если это просто данные, то лучше использовать ```struct```. Тогда ```public``` не нужен.

2024-12-24 21:51 UTC, closed without merging