Структурирование проекта, рефактор CMake
anunknowperson/renderlib pull request #39
Opened 2024-10-11 01:30 UTC by metrapoliten

- Теперь сорсы проекта в основном лежат в /src. Однако IController.h как public header, уверен,что на данный момент это сделано неправильно.
- Разбитие сборки по разным CMakeLists.txt. Теперь можно собрать библиотеку отдельно от исполняемого файла (он лежит в demos).
- Добавление возможности создания тестов при помощи GTest.
- Быстрый фикс скрипта сборки шейдеров.

2024-10-11 15:44 UTC, metrapoliten commented
Надо изменить версию CMake на 3.14, т.к. FetchContent_MakeAvailable

2024-10-11 15:45 UTC, metrapoliten commented
Если перекинуть код ниже в корневой CMakeLists, то программа билдится
`find_package(SDL2 CONFIG REQUIRED)
target_link_libraries(${PROJECT_NAME}
        PRIVATE
        $<TARGET_NAME_IF_EXISTS:SDL2::SDL2main>
        $<IF:$<TARGET_EXISTS:SDL2::SDL2>,SDL2::SDL2,SDL2::SDL2-static>
)`

2024-10-12 11:43 UTC, Tydik42 requested changes
Нужно исправить генерацию конфига. И, наверное, хорошо бы добавить compile options, но это можно сделать отедльной задачей и потом залить в другом pr'е.

2024-10-12 11:43 UTC, Tydik42 commented on CMakeLists.txt
> -configure_file(config.h.in ${CMAKE_CURRENT_SOURCE_DIR}/include/core/config.h @ONLY)
Генерации конфига теперь нет. Можно добавить в корневой `CmakeLists.txt` что-нибудь по типу:
```cmake
set(ASSETS_DIR "${CMAKE_SOURCE_DIR}/assets")
configure_file(src/config.h.in ${CMAKE_CURRENT_SOURCE_DIR}/src/include/core/config.h @ONLY)
```

Либо вынести генерацию конфига в `CmakeLists.txt` в сорсах.

2024-10-12 11:43 UTC, Tydik42 commented on cmake/linkPackages.cmake
Не знаю, насколько это хорошая практика, но читаемость от такого решения улучшается.

2024-10-12 11:43 UTC, Tydik42 commented on include/core/config.h
Это нужно удалить.

2024-10-12 11:43 UTC, Tydik42 commented on src/include/core/config.h
Это должно лежать в `src/include/core/.gitignore`

2024-10-12 11:43 UTC, Tydik42 commented on src/scene/CMakeLists.txt
Нет никаких альтернатив для GLOB_RECURSE? Явное указание всех сорсов выгдялит не очень удобно, но могу быть не прав.

2024-10-12 11:46 UTC, Tydik42 commented on src/graphics/CMakeLists.txt
> +target_sources(${PROJECT_NAME}
Нет никаких альтернатив для GLOB_RECURSE? Явное указание всех сорсов выгдялит не очень удобно, но могу быть не прав.

2024-10-12 11:47 UTC, Tydik42 commented on src/core/CMakeLists.txt
> +)
Нет никаких альтернатив для GLOB_RECURSE? Явное указание всех сорсов выгдялит не очень удобно, но могу быть не прав.

2024-10-12 12:58 UTC, metrapoliten commented
> Нужно исправить генерацию конфига. И, наверное, хорошо бы добавить compile options, но это можно сделать отедльной задачей и потом залить в другом pr'е.

Что ты понимаешь под исправлением генерации конфига?

2024-10-12 13:06 UTC, metrapoliten commented on CMakeLists.txt
> -configure_file(config.h.in ${CMAKE_CURRENT_SOURCE_DIR}/include/core/config.h @ONLY)
Эти строчки теперь лежат в `src/CMakeLists.txt`

2024-10-12 13:42 UTC, metrapoliten commented on cmake/linkPackages.cmake
Это ты о чём?

2024-10-12 13:48 UTC, metrapoliten commented on src/core/CMakeLists.txt
> +)
[Документация](https://cmake.org/cmake/help/latest/command/file.html#filesystem) CMake не рекомендует использовать GLOB

2024-10-16 13:09 UTC, anunknowperson approved these changes

2024-10-16 18:14 UTC, Tydik42 approved these changes

2024-10-16 18:22 UTC, merged