Camera
anunknowperson/renderlib pull request #44
Opened 2024-10-19 09:41 UTC by DanielKorbelainen

Final version of the Camera class with full functionality compliant with the MVC pattern.
The core functionality resides within the Camera class itself, while its controller has been separated to handle all additional functionalities.

2024-10-21 04:26 UTC, metrapoliten commented on src/include/core/CameraController.h
> +    Camera& camera; // Ссылка на камеру
добавь префикс _ для приватных данных

2024-10-21 06:05 UTC, metrapoliten requested changes
- Кажется, ты не прошёлся clang-format по файлам
- Добавь описания к методам в хедерах. Например, непонятно аргумент-угол в радиусах или радианах, какие значения в камере по дефолту?

2024-10-21 08:56 UTC, DanielKorbelainen commented on src/include/core/CameraController.h
> +    void processSDLEvent(const SDL_Event& event); // Метод для обработки событий SDL
Метод processSDLEvent не должен быть в Camera, потому что он не связан с хранением данных камеры, а с управлением этими данными, так что это относится к контроллеру. 
Методы, связанные с матрицей вида, и правда скорее относятся к Camera, потому что хранят ее данные.

2024-10-23 17:18 UTC, DanielKorbelainen commented on src/core/CameraController.cpp
> +    const float moveSpeed = 0.1f;  // Скорость движения камеры
Пока что без особых причин. По результатам тестов надо будет понять какие значения будут оптимальными. Или, что еще лучше, сделать ее регулируемой. Но пока что не думаю что это имеет большое значение.

2024-10-23 17:30 UTC, DanielKorbelainen commented on src/include/scene/Camera.h
> +    glm::vec3 position;
Действительно. Но я уже этоисправил - перенес, как и положено, поля в private.

2024-10-25 06:38 UTC, metrapoliten commented on src/include/core/CameraController.h
> +    void processSDLEvent(const SDL_Event& event); // Метод для обработки событий SDL
processSDLEvent() отвечает за то, на какие кнопки нажать, чтобы поменять состояние камеры, а это поведение, которое должно задаваться пользоателем библиотеки.

2024-10-25 12:16 UTC, DanielKorbelainen commented on src/include/core/CameraController.h
> +    void processSDLEvent(const SDL_Event& event); // Метод для обработки событий SDL
Хорошо, пусть будет так.

2024-11-17 08:58 UTC, closed without merging