Warnings cleanup
anunknowperson/renderlib pull request #49
Opened 2024-11-12 12:30 UTC by Tydik42

2024-11-22 23:39 UTC, metrapoliten requested changes

2024-11-22 23:39 UTC, metrapoliten commented on src/graphics/vulkan/vk_initializers.cpp
> +        [[maybe_unused]] uint32_t queueFamilyIndex, VkCommandPoolCreateFlags flags /*= 0*/) {
Почему просто не убрать параметр?

2024-11-22 23:39 UTC, metrapoliten commented on src/graphics/vulkan/vk_loader.cpp
> +            auto initial_vtx = static_cast<uint32_t>(vertices.size());
Почему мы делаем каст от, скорее всего, `size_t` к `u32`?

2024-11-22 23:39 UTC, metrapoliten commented on src/graphics/vulkan/vk_loader.cpp
> +    file.descriptorPool.init(engine->_device, static_cast<uint32_t>(gltf.materials.size()), sizes);
То же, что выше

2024-11-22 23:39 UTC, metrapoliten commented on src/graphics/vulkan/vk_loader.cpp
> +            auto initial_vtx = static_cast<uint32_t>(vertices.size());
То же, что выше

2024-11-22 23:39 UTC, metrapoliten commented on src/graphics/vulkan/vk_pipelines.cpp
> +    file.read((char*)buffer.data(), static_cast<long>(fileSize));
Если каст вообще нужен, то использовать std::streamsize, long разной ширины на разных системах и не обязательно соответствует std::streamsize

2024-11-22 23:39 UTC, metrapoliten commented on src/graphics/vulkan/vk_pipelines.cpp
> +    auto fileSize = (size_t)file.tellg();
Зачем нам каст к size_t? Кажется, дальше по коду это нигде не используется

2024-12-05 11:53 UTC, Tydik42 commented on src/graphics/vulkan/vk_initializers.cpp
> +        [[maybe_unused]] uint32_t queueFamilyIndex, VkCommandPoolCreateFlags flags /*= 0*/) {
Он будет нужен (по крайней мере в vk_guide так сказано)

2024-12-05 16:25 UTC, Tydik42 commented on src/graphics/vulkan/vk_loader.cpp
> +            auto initial_vtx = static_cast<uint32_t>(vertices.size());
для ```fastgltf::iterateAccessor<std::uint32_t>``` нужен именно unsigned int. И в еще одной части нжуен unsigned int. Закастить unsigned long к unsigned int. Исправление indices на ```std::vector<size_t>``` приводило к большому количеству ошибок в других частях кода, поэтому это решение -- самое стабильное.

2024-12-05 16:37 UTC, Tydik42 commented on src/graphics/vulkan/vk_pipelines.cpp
> +    auto fileSize = (size_t)file.tellg();
Нам нужен unsigned, чтобы передать в ```std::vector<uint32_t> buffer```. Исправил, путем каста fileSize к uint32_t, от этого ничего не должо сломаться.

2024-12-05 16:39 UTC, Tydik42 commented on src/graphics/vulkan/vk_pipelines.cpp
> +    file.read((char*)buffer.data(), static_cast<long>(fileSize));
исправил (ниже)

2024-12-05 16:53 UTC, Tydik42 commented on CMakePresets.json
> +        "CMAKE_CXX_FLAGS_INIT": "/W4 /wd4700"
Эквивалент ```-Wno-missing-field-initializers```
В Vk<name> структурах нам либо не нужно инициализировать все параметры, либо они менюятся, либо мы вообще не знаем, что нужно инициализировать, поэтому этот флаг убрал.

2024-12-05 16:59 UTC, Tydik42 commented on src/core/ControllerImpl.cpp
> +    _model->setMeshTransform(&"cube"[name], scale * translation);
Исправил

2024-12-06 03:39 UTC, metrapoliten commented on CMakePresets.json
> +        "CMAKE_CXX_FLAGS_INIT": "/W4 /wd4700"
Как понял, это не экивалент, но ладно

2024-12-06 04:08 UTC, metrapoliten requested changes

2024-12-06 04:08 UTC, metrapoliten commented on src/graphics/vulkan/vk_pipelines.cpp
> +    auto fileSize = static_cast<uint32_t>(file.tellg());
Просто убери здесь static_cast

А ещё надо проверять, чтобы размер буфера был ненулевой, т.к. если 0, то buffer.data может вернуть nullptr

2024-12-06 17:00 UTC, metrapoliten commented on src/graphics/vulkan/vk_pipelines.cpp
> +    auto fileSize = static_cast<uint32_t>(file.tellg());
`
const auto fileSize = file.tellg();
std::vector<uint32_t> buffer(fileSize / sizeof(uint32_t));
file.read(reinterpret_cast<char*>(buffer.data()), fileSize);
```

2024-12-06 17:04 UTC, metrapoliten requested changes
Добавь `-Wold-style-cast` и почисти

2024-12-07 20:53 UTC, Tydik42 commented on src/graphics/vulkan/vk_pipelines.cpp
> +    auto fileSize = static_cast<uint32_t>(file.tellg());
Нам все равно нужно кастить fileSize к uint32_t, потому что иначе ругается. Но перед этим и правда нужно добавить проверку

2024-12-09 16:55 UTC, merged

2024-12-10 13:45 UTC, anunknowperson commented
P.S. Ваня Похабов, если ты это читаешь, то знай, ты - лучший!