Camera (new)
anunknowperson/renderlib pull request #50
Opened 2024-11-17 08:59 UTC by DanielKorbelainen

New Pull Request for Camera due to old one not working properly.

2024-12-05 17:07 UTC, Tydik42 commented on CMakeLists.txt
Не нужно вносить правки в CmakeLists.txt в этой ветке. В принципе, эти правки не нужны были

2024-12-05 18:17 UTC, DanielKorbelainen commented on CMakeLists.txt
> +        src/core/CameraController.cpp)
Про камеру убрал, остальное думаю понятно что это клэнг какой-нибудь а не я

2024-12-06 04:18 UTC, metrapoliten requested changes
Есть ли возможность без лишних заморочек CameraController быть, где он должен быть, - в контроллере, а не в модели?

2024-12-06 04:18 UTC, metrapoliten commented on vcpkg.json
> +    "gtest"
Этого здесь не должно быть, т.к. gtest устанавливается с помощью CMake

2024-12-06 16:13 UTC, DanielKorbelainen commented on vcpkg.json
> +    "gtest"
Нет :)

2024-12-06 16:53 UTC, metrapoliten commented on vcpkg.json
> +    "gtest"
убери пока что, потом отдельным PR изменим

2025-02-20 22:28 UTC, metrapoliten commented
Тесты вероятно не работают, т.к. ты удалил `add_gtest`. Предлагаю тесты сохранить в отдельную ветку, а из этого PR убрать.

2025-04-04 18:13 UTC, DanielKorbelainen commented
- Add hierarchical camera architecture (ICamera, BaseCamera, Perspective/Orthographic):
Structured camera system was implemented, with a base interface (ICamera) and derived classes (BaseCamera, PerspectiveCamera, OrthographicCamera) to handle different types of cameras.

- Implement camera controllers with FPS and orbit navigation modes:
Two types of camera controllers were added: one for first-person shooter (FPS) style navigation (FPSCameraController) and another for orbit-style navigation (OrbitCameraController).

- Add SDL event handling and input translation system:
Functionality to handle SDL events and translate them into a custom InputEvent format, allowing the camera controllers to respond to user input.

- Support mouse/keyboard navigation, zooming, and panning:
Camera controller support various input methods, including mouse and keyboard for navigation, zooming, and panning actions.

- Fix compilation errors and warnings:
Any existing compilation errors and warnings were resolved, ensuring that the code compiles successfully without issues

2026-03-18 20:02 UTC, closed without merging