Выделение MeshController
anunknowperson/renderlib pull request #52
Opened 2024-11-30 08:31 UTC by metrapoliten

- Создан класс для управления мешами (MeshController). У каждого добавленного меша есть свой render-id
- Вынесены из vk_engine.cpp/h вещи, связанные с мешами
- Изменена логика запуска движка (методы ICrlr, IView, IModel и их имплементации), чтобы проверить работоспособность MeshController
- Дробление больших функций, приведение кода к более "презентабельному" виду

2024-12-06 07:10 UTC, AnthonyRulez requested changes
Определитесь с код стайлом и используйте единообразное именование методов.

2024-12-25 09:10 UTC, Tydik42 commented
This pull request includes several changes to the `demo/main.cpp`, `IController` interface, and various core and graphics-related files to enhance functionality and refactor the codebase. The most important changes include introducing new methods for cube creation and updates, modifying the `IController` interface, and refactoring the `ControllerImpl` and `ViewImpl` classes.

### Enhancements to cube functionality:
* [`demo/main.cpp`](diffhunk://#diff-2afd463a93cdfd5e430506899a31972792e8b09867a624ca51d3976d325f1a22L1-R93): Added `createCubes`, `updateCube`, and `updateCubes` functions to handle cube creation and updates.
* [`src/core/MeshController.cpp`](diffhunk://#diff-6b83ea5ff69ac2f209e3de18ace8689cf229ae7bd65b39d4297abde9310eaef3R1-R36): Implemented `MeshController` class to manage mesh operations such as creation, deletion, and transformation.

### Changes to `IController` interface:
* [`include/IController.h`](diffhunk://#diff-5a0c08bcb99a5dc1860f3916233507f996fa4c7dd6ccc5f94f1bc08ee15a7e75L26-R49): Removed `init` method, added `run` method to render a new frame, and introduced `getMeshController` method to interact with meshes.

### Refactoring of core classes:
* [`src/core/ControllerImpl.cpp`](diffhunk://#diff-b774e0cf3aecf94b2c7542f290f8c32aad3a82b1e7848051266af16a46d27808R5-R31): Refactored `ControllerImpl` to include `run` and `update` methods and manage mesh controller creation.
* [`src/core/ViewImpl.cpp`](diffhunk://#diff-f222de9e38ac5e52562b480d23959ed33528a8ae16e8d668485f32397bdc2dbcL20-R31): Simplified `ViewImpl` by removing cube creation logic and delegating event processing to a new `process_event` method. [[1]](diffhunk://#diff-f222de9e38ac5e52562b480d23959ed33528a8ae16e8d668485f32397bdc2dbcL20-R31) [[2]](diffhunk://#diff-f222de9e38ac5e52562b480d23959ed33528a8ae16e8d668485f32397bdc2dbcL88-R49)

### Build system updates:
* [`src/core/CMakeLists.txt`](diffhunk://#diff-c45a6adabc811ade80459a55314772e4054cdcf7804228bb714231f9da5ec7eaL5-R5): Replaced `Mesh.cpp` with `MeshController.cpp` in the target sources.
* [`src/graphics/CMakeLists.txt`](diffhunk://#diff-11a59fa4b532ee3177beccd92e47861565367f6e4738f3cd38ff113758b3c12aR3-L7): Added `MeshNode.cpp` and `RenderableGLTF.cpp` to the target sources.

### Vulkan engine updates:
* [`src/graphics/vulkan/vk_engine.cpp`](diffhunk://#diff-236002fd473af0c525b664e7cc694d543b66dd5c0ccf65a136305e64fcf61545R3-R23): Removed redundant mesh loading and updated `draw` and `update` methods to accept `IModel::Ptr` parameter. [[1]](diffhunk://#diff-236002fd473af0c525b664e7cc694d543b66dd5c0ccf65a136305e64fcf61545R3-R23) [[2]](diffhunk://#diff-236002fd473af0c525b664e7cc694d543b66dd5c0ccf65a136305e64fcf61545L95) [[3]](diffhunk://#diff-236002fd473af0c525b664e7cc694d543b66dd5c0ccf65a136305e64fcf61545L495-L500) [[4]](diffhunk://#diff-236002fd473af0c525b664e7cc694d543b66dd5c0ccf65a136305e64fcf61545L1008-R1010) [[5]](diffhunk://#diff-236002fd473af0c525b664e7cc694d543b66dd5c0ccf65a136305e64fcf61545L1184-R1190) [[6]](diffhunk://#diff-236002fd473af0c525b664e7cc694d543b66dd5c0ccf65a136305e64fcf61545L1396-R1397)

2024-12-25 09:40 UTC, Tydik42 approved these changes

2025-03-06 02:38 UTC, closed without merging

2025-03-06 02:38 UTC, metrapoliten commented
Не удаляйте ветку