Move out pipelines from vk_engine class
anunknowperson/renderlib pull request #55
Opened 2024-12-24 21:07 UTC by anunknowperson

supersedes https://github.com/anunknowperson/renderlib/pull/37

2024-12-24 23:00 UTC, metrapoliten requested changes

2024-12-24 23:00 UTC, metrapoliten commented on CMakePresets.json
> +        "CMAKE_COMPILE_WARNING_AS_ERROR": "OFF"
В чём причина? Не должно изменяться.

2024-12-24 23:00 UTC, metrapoliten commented on demo/assets/basicmesh.glb
Выглядит подозрительно, этот файл точно должен измениться?

2024-12-24 23:00 UTC, metrapoliten commented on include/core/config.h
Этого файла не должно быть в коммите. Он ведь в .gitignore лежит. Странно, что вообще добавился.

2024-12-24 23:00 UTC, metrapoliten commented on src/graphics/vulkan/pipelines.cpp
> +                                                   const char* path,
std::filesystem::path или relative_path

2024-12-24 23:00 UTC, metrapoliten commented on src/graphics/vulkan/pipelines.cpp
> +    const char* cPath = str.c_str();  // warning: potential dangling pointer in c string if str leaves scope. �~�� �r�����t�u ������ �~�����}, ���p�{ �{�p�{ �������|�u �x�p�s�����x�{�y �������� �q���
:)

2024-12-24 23:00 UTC, metrapoliten commented on src/include/graphics/vulkan/pipelines.h
> +    void init(VkDevice device,
Почему не используем конструктор?

2024-12-24 23:00 UTC, metrapoliten commented on src/include/graphics/vulkan/pipelines.h
> +    void destroy();
Почему не используем деструктор?

2025-03-19 20:19 UTC, Fra1sse reviewed
нужно исправить мерж конфликты и убрать лишний файл

2025-03-19 20:19 UTC, Fra1sse commented on include/core/config.h
лишний файл

2025-04-24 08:42 UTC, Tydik42 approved these changes
LGTM

2025-04-24 08:44 UTC, merged